### ISSUE TITLE
Problem with epitopedia in a cluster

### ISSUE THREAD

**Issue by mile-brem** [cbalbin-FIU/Epitopedia#1]
Hi,

I am in the process of trying to use epitopedia in a cluster at my institution. 

To explain the steps I have done so far:
- I pulled a singularity image to create a container of epitopedia onto my cluster
- I downloaded the PDB in mmCIF (unzipped) to my cluster in a directory known as /cephfs/ as well as the EPI_DB in the linked zip file (Just to clarify, I can skip the step of database generation as you have provided the final database regardless?;again unzipped in my cluster)
- I have created a slurm job (attached) using run_epitopedia and my protein of interest 5ELI

Now here is where I run into my problem:
- I get an error message that the database cannot be opened (attached)

At am at a loss as to where the issue might be and I hope someone might be able to shed light. It looks like it's a problem with perhaps the plugin running on a cluster system rather than a local system maybe?

Thanks,
[TREM2_log.log](https://github.com/user-attachments/files/17229277/TREM2_log.log)

Miles
[TREM2_search - Copy.txt](https://github.com/user-attachments/files/17229297/TREM2_search.-.Copy.txt)

**Comment by LouC19** [comment]
Dear Chris,

I am trying to run epitopedia, but have come up with an error I can't figure out. I ran the following (as well as several variations):

 python3 Epitopedia/docker/run_epitopedia.py \
/mnt/e/Epitopedia/output/ \
/mnt/e/mmCIF/vh/ \
/mnt/e/EpitopediaDB/epitopedia_data/ \
--afdb-dir /mnt/e/AFhuman/ \
--PDB-IDS 6VH6 \
--taxid-filter 10376

And received the error:

Traceback (most recent call last):
  File "/usr/local/bin/run_epitopedia", line 33, in <module>
    sys.exit(load_entry_point('Epitopedia==1.1', 'console_scripts', 'run_epitopedia')())
  File "/usr/local/lib/python3.9/site-packages/Epitopedia-1.1-py3.9.egg/epitopedia/run_epitopedia.py", line 42, in main
IndexError: list index out of range

Would you be able to help me figure out what this means and how to resolve it? 

Many thanks,
Luke
